permissions:
  contents: write

name: Parse CBR Data

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run parser
        run: node parser.js

      - name: Commit result
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "update data" || echo "no changes"
          git push